- id: stale-version
  name: stale versions
  description: Ensure that a version has been bumped if required
  entry: stale_version
  language: python
  require_serial: true
  pass_filenames: false
  files: ''  # all
  types:
    - text
- id: no-todos
  name: no todos
  description: Ensure that are no TODO comments
  entry: no_todos
  language: python
  require_serial: false
  pass_filenames: false
  files: ''  # all
  types:
    - text
